version: '3'

services:

  postgres:
    image: postgres:10
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 9876:5432
    environment:
      - POSTGRES_USER=beanstalk
      - POSTGRES_PASSWORD=beanstalk
      - POSTGRES_DB=beanstalk

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - TEST=true
      - BEANSTALK_HOST=localhost
      - BEANSTALK_PORT=8080
      - BEANSTALK_POSTGRESHOST=postgres
      - BEANSTALK_POSTGRESPORT=5432
      - BEANSTALK_POSTGRESUSER=beanstalk
      - BEANSTALK_POSTGRESPASS=beanstalk
      - BEANSTALK_POSTGRESDB=beanstalk
